import 'package:arxiv_mobile/models/category_group.dart';
import 'package:flutter/material.dart';

class Category {
  Category({
    this.id,
    this.title,
    this.isSelected = false,
  }) {
    this.categoryGroup = CategoryGroup.categoryGroupMap[this.id.split('.')[0]];
  }

  String id;
  String title;
  bool isSelected;
  CategoryGroup categoryGroup;

  static Color getColour(String id) => categoryMap[id].categoryGroup?.colour ?? Colors.grey;

  static List<Category> categoryList = <Category>[
    Category(id: "astro-ph", title: "Astrophysics"),
    Category(
        id: "astro-ph.CO", title: "Cosmology and Nongalactic Astrophysics"),
    Category(id: "astro-ph.EP", title: "Earth and Planetary Astrophysics"),
    Category(id: "astro-ph.GA", title: "Astrophysics of Galaxies"),
    Category(id: "astro-ph.HE", title: "High Energy Astrophysical Phenomena"),
    Category(
        id: "astro-ph.IM",
        title: "Instrumentation and Methods for Astrophysics"),
    Category(id: "astro-ph.SR", title: "Solar and Stellar Astrophysics"),
    Category(
        id: "cond-mat.dis-nn", title: "Disordered Systems and Neural Networks"),
    Category(id: "cond-mat.mes-hall", title: "Mesoscale and Nanoscale Physics"),
    Category(id: "cond-mat.mtrl-sci", title: "Materials Science"),
    Category(id: "cond-mat.other", title: "Other Condensed Matter"),
    Category(id: "cond-mat.quant-gas", title: "Quantum Gases"),
    Category(id: "cond-mat.soft", title: "Soft Condensed Matter"),
    Category(id: "cond-mat.stat-mech", title: "Statistical Mechanics"),
    Category(id: "cond-mat.str-el", title: "Strongly Correlated Electrons"),
    Category(id: "cond-mat.supr-con", title: "Superconductivity"),
    Category(id: "cs.AI", title: "Artificial Intelligence"),
    Category(id: "cs.AR", title: "Hardware Architecture"),
    Category(id: "cs.CC", title: "Computational Complexity"),
    Category(
        id: "cs.CE", title: "Computational Engineering, Finance, and Science"),
    Category(id: "cs.CG", title: "Computational Geometry"),
    Category(id: "cs.CL", title: "Computation and Language"),
    Category(id: "cs.CR", title: "Cryptography and Security"),
    Category(id: "cs.CV", title: "Computer Vision and Pattern Recognition"),
    Category(id: "cs.CY", title: "Computers and Society"),
    Category(id: "cs.DB", title: "Databases"),
    Category(
        id: "cs.DC", title: "Distributed, Parallel, and Cluster Computing"),
    Category(id: "cs.DL", title: "Digital Libraries"),
    Category(id: "cs.DM", title: "Discrete Mathematics"),
    Category(id: "cs.DS", title: "Data Structures and Algorithms"),
    Category(id: "cs.ET", title: "Emerging Technologies"),
    Category(id: "cs.FL", title: "Formal Languages and Automata Theory"),
    Category(id: "cs.GL", title: "General Literature"),
    Category(id: "cs.GR", title: "Graphics"),
    Category(id: "cs.GT", title: "Computer Science and Game Theory"),
    Category(id: "cs.HC", title: "Human-Computer Interaction"),
    Category(id: "cs.IR", title: "Information Retrieval"),
    Category(id: "cs.IT", title: "Information Theory"),
    Category(id: "cs.LG", title: "Learning"),
    Category(id: "cs.LO", title: "Logic in Computer Science"),
    Category(id: "cs.MA", title: "Multiagent Systems"),
    Category(id: "cs.MM", title: "Multimedia"),
    Category(id: "cs.MS", title: "Mathematical Software"),
    Category(id: "cs.NA", title: "Numerical Analysis"),
    Category(id: "cs.NE", title: "Neural and Evolutionary Computing"),
    Category(id: "cs.NI", title: "Networking and Internet Architecture"),
    Category(id: "cs.OH", title: "Other Computer Science"),
    Category(id: "cs.OS", title: "Operating Systems"),
    Category(id: "cs.PF", title: "Performance"),
    Category(id: "cs.PL", title: "Programming Languages"),
    Category(id: "cs.RO", title: "Robotics"),
    Category(id: "cs.SC", title: "Symbolic Computation"),
    Category(id: "cs.SD", title: "Sound"),
    Category(id: "cs.SE", title: "Software Engineering"),
    Category(id: "cs.SI", title: "Social and Information Networks"),
    Category(id: "cs.SY", title: "Systems and Control"),
    Category(id: "econ.EM", title: "Econometrics"),
    Category(id: "eess.AS", title: "Audio and Speech Processing"),
    Category(id: "eess.IV", title: "Image and Video Processing"),
    Category(id: "eess.SP", title: "Signal Processing"),
    Category(id: "gr-qc", title: "General Relativity and Quantum Cosmology"),
    Category(id: "hep-ex", title: "High Energy Physics - Experiment"),
    Category(id: "hep-lat", title: "High Energy Physics - Lattice"),
    Category(id: "hep-ph", title: "High Energy Physics - Phenomenology"),
    Category(id: "hep-th", title: "High Energy Physics - Theory"),
    Category(id: "math.AC", title: "Commutative Algebra"),
    Category(id: "math.AG", title: "Algebraic Geometry"),
    Category(id: "math.AP", title: "Analysis of PDEs"),
    Category(id: "math.AT", title: "Algebraic Topology"),
    Category(id: "math.CA", title: "Classical Analysis and ODEs"),
    Category(id: "math.CO", title: "Combinatorics"),
    Category(id: "math.CT", title: "Category Theory"),
    Category(id: "math.CV", title: "Complex Variables"),
    Category(id: "math.DG", title: "Differential Geometry"),
    Category(id: "math.DS", title: "Dynamical Systems"),
    Category(id: "math.FA", title: "Functional Analysis"),
    Category(id: "math.GM", title: "General Mathematics"),
    Category(id: "math.GN", title: "General Topology"),
    Category(id: "math.GR", title: "Group Theory"),
    Category(id: "math.GT", title: "Geometric Topology"),
    Category(id: "math.HO", title: "History and Overview"),
    Category(id: "math.IT", title: "Information Theory"),
    Category(id: "math.KT", title: "K-Theory and Homology"),
    Category(id: "math.LO", title: "Logic"),
    Category(id: "math.MG", title: "Metric Geometry"),
    Category(id: "math.MP", title: "Mathematical Physics"),
    Category(id: "math.NA", title: "Numerical Analysis"),
    Category(id: "math.NT", title: "Number Theory"),
    Category(id: "math.OA", title: "Operator Algebras"),
    Category(id: "math.OC", title: "Optimization and Control"),
    Category(id: "math.PR", title: "Probability"),
    Category(id: "math.QA", title: "Quantum Algebra"),
    Category(id: "math.RA", title: "Rings and Algebras"),
    Category(id: "math.RT", title: "Representation Theory"),
    Category(id: "math.SG", title: "Symplectic Geometry"),
    Category(id: "math.SP", title: "Spectral Theory"),
    Category(id: "math.ST", title: "Statistics Theory"),
    Category(id: "math-ph", title: "Mathematical Physics"),
    Category(id: "nlin.AO", title: "Adaptation and Self-Organizing Systems"),
    Category(id: "nlin.CD", title: "Chaotic Dynamics"),
    Category(id: "nlin.CG", title: "Cellular Automata and Lattice Gases"),
    Category(id: "nlin.PS", title: "Pattern Formation and Solitons"),
    Category(id: "nlin.SI", title: "Exactly Solvable and Integrable Systems"),
    Category(id: "nucl-ex", title: "Nuclear Experiment"),
    Category(id: "nucl-th", title: "Nuclear Theory"),
    Category(id: "physics.acc-ph", title: "Accelerator Physics"),
    Category(id: "physics.ao-ph", title: "Atmospheric and Oceanic Physics"),
    Category(id: "physics.app-ph", title: "Applied Physics"),
    Category(id: "physics.atm-clus", title: "Atomic and Molecular Clusters"),
    Category(id: "physics.atom-ph", title: "Atomic Physics"),
    Category(id: "physics.bio-ph", title: "Biological Physics"),
    Category(id: "physics.chem-ph", title: "Chemical Physics"),
    Category(id: "physics.class-ph", title: "Classical Physics"),
    Category(id: "physics.comp-ph", title: "Computational Physics"),
    Category(
        id: "physics.data-an",
        title: "Data Analysis, Statistics and Probability"),
    Category(id: "physics.ed-ph", title: "Physics Education"),
    Category(id: "physics.flu-dyn", title: "Fluid Dynamics"),
    Category(id: "physics.gen-ph", title: "General Physics"),
    Category(id: "physics.geo-ph", title: "Geophysics"),
    Category(id: "physics.hist-ph", title: "History and Philosophy of Physics"),
    Category(id: "physics.ins-det", title: "Instrumentation and Detectors"),
    Category(id: "physics.med-ph", title: "Medical Physics"),
    Category(id: "physics.optics", title: "Optics"),
    Category(id: "physics.plasm-ph", title: "Plasma Physics"),
    Category(id: "physics.pop-ph", title: "Popular Physics"),
    Category(id: "physics.soc-ph", title: "Physics and Society"),
    Category(id: "physics.space-ph", title: "Space Physics"),
    Category(id: "q-bio.BM", title: "Biomolecules"),
    Category(id: "q-bio.CB", title: "Cell Behavior"),
    Category(id: "q-bio.GN", title: "Genomics"),
    Category(id: "q-bio.MN", title: "Molecular Networks"),
    Category(id: "q-bio.NC", title: "Neurons and Cognition"),
    Category(id: "q-bio.OT", title: "Other Quantitative Biology"),
    Category(id: "q-bio.PE", title: "Populations and Evolution"),
    Category(id: "q-bio.QM", title: "Quantitative Methods"),
    Category(id: "q-bio.SC", title: "Subcellular Processes"),
    Category(id: "q-bio.TO", title: "Tissues and Organs"),
    Category(id: "q-fin.CP", title: "Computational Finance"),
    Category(id: "q-fin.EC", title: "Economics"),
    Category(id: "q-fin.GN", title: "General Finance"),
    Category(id: "q-fin.MF", title: "Mathematical Finance"),
    Category(id: "q-fin.PM", title: "Portfolio Management"),
    Category(id: "q-fin.PR", title: "Pricing of Securities"),
    Category(id: "q-fin.RM", title: "Risk Management"),
    Category(id: "q-fin.ST", title: "Statistical Finance"),
    Category(id: "q-fin.TR", title: "Trading and Market Microstructure"),
    Category(id: "quant-ph", title: "Quantum Physics"),
    Category(id: "stat.AP", title: "Applications"),
    Category(id: "stat.CO", title: "Computation"),
    Category(id: "stat.ME", title: "Methodology"),
    Category(id: "stat.ML", title: "Machine Learning"),
    Category(id: "stat.OT", title: "Other Statistics"),
    Category(id: "stat.TH", title: "Statistics Theory"),
  ];

  static final Map<String, Category> categoryMap =
      Map.fromIterable(categoryList, key: (cat) => cat.id, value: (cat) => cat);

  static final List<String> categories =
      categoryMap.keys.toList(growable: false);
}
